// Comprehensive crop dataset for the Field Add wizard's crop picker.
// Grouped by category. Each crop optionally lists varieties / sub-varieties.
// Curated to cover globally significant cereals, pulses, oilseeds, vegetables,
// fruits, nuts, herbs, spices, beverage/cash crops, fiber crops, fodder,
// mushrooms and ornamentals. Add freely — the picker just iterates this array.

export const CROP_CATEGORIES = [
  {
    name: "Cereals & Grains",
    icon: "ri-plant-line",
    crops: [
      { name: "Rice", varieties: ["Basmati", "Jasmine", "Long Grain", "Short Grain", "Arborio", "Sona Masuri", "Ponni", "Black Rice", "Brown Rice", "Wild Rice", "Glutinous (Sticky)", "Red Rice", "Carolina Gold"] },
      { name: "Wheat", varieties: ["Hard Red Winter", "Hard Red Spring", "Soft Red Winter", "Hard White", "Soft White", "Durum", "Spelt", "Emmer", "Einkorn", "Khorasan (Kamut)"] },
      { name: "Maize (Corn)", varieties: ["Dent", "Flint", "Sweet Corn", "Popcorn", "Flour Corn", "Waxy", "Baby Corn", "Field Corn", "Blue Corn"] },
      { name: "Barley", varieties: ["Two-row", "Six-row", "Hulless", "Malting", "Feed"] },
      { name: "Oats", varieties: ["Common", "Hulless", "Red", "Black", "Naked"] },
      { name: "Rye", varieties: ["Winter Rye", "Spring Rye"] },
      { name: "Triticale" },
      { name: "Sorghum", varieties: ["Grain Sorghum (Milo)", "Forage Sorghum", "Sweet Sorghum", "Broomcorn"] },
      { name: "Millet", varieties: ["Pearl (Bajra)", "Finger (Ragi)", "Foxtail", "Proso", "Barnyard", "Kodo", "Little Millet", "Browntop"] },
      { name: "Teff" },
      { name: "Buckwheat" },
      { name: "Quinoa", varieties: ["White", "Red", "Black"] },
      { name: "Amaranth" },
      { name: "Fonio" },
      { name: "Wild Rice" },
    ],
  },
  {
    name: "Pulses & Legumes",
    icon: "ri-seedling-line",
    crops: [
      { name: "Soybean", varieties: ["Yellow", "Black", "Edamame", "Non-GMO Food Grade"] },
      { name: "Chickpea", varieties: ["Desi (Bengal Gram)", "Kabuli", "Green"] },
      { name: "Lentil", varieties: ["Red (Masoor)", "Green", "Brown", "Black (Beluga)", "Puy", "Yellow"] },
      { name: "Pea", varieties: ["Garden Pea", "Snow Pea", "Snap Pea", "Field/Dry Pea", "Split Pea"] },
      { name: "Pigeon Pea (Tur/Arhar)" },
      { name: "Mung Bean (Green Gram)" },
      { name: "Urad (Black Gram)" },
      { name: "Cowpea (Black-eyed Pea)", varieties: ["Black-eyed", "Crowder", "Yardlong"] },
      { name: "Common Bean", varieties: ["Kidney", "Pinto", "Navy", "Black", "Cranberry", "Great Northern", "Lima", "Mayocoba", "Anasazi"] },
      { name: "Faba Bean (Broad Bean)" },
      { name: "Adzuki Bean" },
      { name: "Lupin", varieties: ["Sweet White", "Narrow-leafed", "Yellow", "Andean (Tarwi)"] },
      { name: "Lablab Bean" },
      { name: "Moth Bean" },
      { name: "Horsegram (Kulthi)" },
      { name: "Bambara Groundnut" },
      { name: "Winged Bean" },
      { name: "Velvet Bean (Mucuna)" },
      { name: "Hyacinth Bean" },
    ],
  },
  {
    name: "Oilseeds",
    icon: "ri-drop-line",
    crops: [
      { name: "Groundnut (Peanut)", varieties: ["Runner", "Virginia", "Spanish", "Valencia"] },
      { name: "Rapeseed / Canola", varieties: ["Winter Canola", "Spring Canola", "HEAR (Industrial)"] },
      { name: "Mustard", varieties: ["Yellow", "Brown", "Black", "Indian Mustard"] },
      { name: "Sunflower", varieties: ["Oilseed (NuSun)", "Confection", "High-oleic"] },
      { name: "Sesame", varieties: ["White", "Black", "Brown"] },
      { name: "Safflower" },
      { name: "Niger Seed" },
      { name: "Linseed (Flax)", varieties: ["Brown", "Golden"] },
      { name: "Castor" },
      { name: "Camelina" },
      { name: "Perilla" },
      { name: "Hemp Seed" },
      { name: "Oil Palm", varieties: ["Tenera", "Dura", "Pisifera"] },
      { name: "Coconut", varieties: ["Tall", "Dwarf", "Hybrid", "King"] },
      { name: "Jojoba" },
    ],
  },
  {
    name: "Vegetables — Leafy",
    icon: "ri-leaf-line",
    crops: [
      { name: "Spinach", varieties: ["Savoy", "Semi-Savoy", "Flat-leaf", "Baby"] },
      { name: "Lettuce", varieties: ["Iceberg", "Romaine", "Butterhead", "Looseleaf", "Batavian", "Oakleaf", "Little Gem"] },
      { name: "Kale", varieties: ["Curly", "Lacinato (Dinosaur)", "Red Russian", "Redbor"] },
      { name: "Swiss Chard", varieties: ["Fordhook Giant", "Rainbow", "Ruby Red"] },
      { name: "Mustard Greens" },
      { name: "Arugula (Rocket)" },
      { name: "Watercress" },
      { name: "Endive / Chicory", varieties: ["Curly Endive", "Escarole", "Belgian Endive", "Radicchio"] },
      { name: "Pak Choi (Bok Choy)" },
      { name: "Napa Cabbage" },
      { name: "Collard Greens" },
      { name: "Amaranth Leaves" },
      { name: "Fenugreek Leaves (Methi)" },
      { name: "Moringa (Drumstick Leaves)" },
      { name: "Sorrel" },
      { name: "Malabar Spinach" },
      { name: "New Zealand Spinach" },
      { name: "Mizuna" },
      { name: "Tatsoi" },
    ],
  },
  {
    name: "Vegetables — Brassicas",
    icon: "ri-leaf-fill",
    crops: [
      { name: "Cabbage", varieties: ["Green", "Red", "Savoy", "Pointed", "January King"] },
      { name: "Cauliflower", varieties: ["White", "Orange", "Purple", "Green (Romanesco)"] },
      { name: "Broccoli", varieties: ["Calabrese", "Sprouting", "Purple Sprouting", "Broccolini"] },
      { name: "Brussels Sprouts" },
      { name: "Kohlrabi", varieties: ["Green", "Purple"] },
      { name: "Turnip", varieties: ["Purple Top", "White", "Hakurei", "Tokyo"] },
      { name: "Rutabaga (Swede)" },
      { name: "Daikon Radish" },
      { name: "Horseradish" },
    ],
  },
  {
    name: "Vegetables — Root & Tuber",
    icon: "ri-plant-fill",
    crops: [
      { name: "Potato", varieties: ["Russet", "Yukon Gold", "Red", "Fingerling", "Purple/Blue", "White", "Kennebec", "Maris Piper", "Desiree"] },
      { name: "Sweet Potato", varieties: ["Orange (Beauregard)", "Purple (Okinawan)", "White", "Japanese (Satsumaimo)"] },
      { name: "Carrot", varieties: ["Nantes", "Imperator", "Chantenay", "Danvers", "Purple", "Rainbow", "Baby"] },
      { name: "Radish", varieties: ["Red Globe", "French Breakfast", "Watermelon", "Black Spanish", "Daikon"] },
      { name: "Beetroot", varieties: ["Detroit Dark Red", "Golden", "Chioggia", "Cylindra"] },
      { name: "Cassava (Manioc/Yuca)", varieties: ["Sweet", "Bitter"] },
      { name: "Yam", varieties: ["White", "Yellow", "Water Yam", "Purple"] },
      { name: "Taro (Colocasia)" },
      { name: "Parsnip" },
      { name: "Ginger" },
      { name: "Turmeric" },
      { name: "Galangal" },
      { name: "Jerusalem Artichoke" },
      { name: "Salsify" },
      { name: "Burdock (Gobo)" },
      { name: "Lotus Root" },
      { name: "Arrowroot" },
      { name: "Tigernut (Chufa)" },
      { name: "Oca" },
      { name: "Ulluco" },
      { name: "Mashua" },
      { name: "Yacón" },
    ],
  },
  {
    name: "Vegetables — Allium",
    icon: "ri-restaurant-line",
    crops: [
      { name: "Onion", varieties: ["Yellow", "Red", "White", "Sweet (Vidalia)", "Spanish", "Cipollini", "Pearl"] },
      { name: "Garlic", varieties: ["Softneck", "Hardneck", "Elephant Garlic", "Black Garlic"] },
      { name: "Shallot" },
      { name: "Leek" },
      { name: "Spring Onion / Scallion" },
      { name: "Chive" },
      { name: "Garlic Chives" },
      { name: "Welsh Onion" },
    ],
  },
  {
    name: "Vegetables — Fruiting",
    icon: "ri-apple-line",
    crops: [
      { name: "Tomato", varieties: ["Beefsteak", "Roma", "Cherry", "Grape", "Heirloom", "San Marzano", "Brandywine", "Plum", "Green Zebra", "Yellow"] },
      { name: "Chilli Pepper", varieties: ["Cayenne", "Jalapeño", "Habanero", "Ghost (Bhut Jolokia)", "Scotch Bonnet", "Bird's Eye", "Serrano", "Thai", "Kashmiri", "Guntur", "Poblano"] },
      { name: "Bell Pepper (Capsicum)", varieties: ["Green", "Red", "Yellow", "Orange", "Purple", "Chocolate"] },
      { name: "Brinjal (Eggplant)", varieties: ["Globe", "Italian", "Japanese", "Thai", "White", "Graffiti", "Indian"] },
      { name: "Okra (Lady's Finger)", varieties: ["Clemson Spineless", "Red Burgundy"] },
      { name: "Tomatillo" },
      { name: "Cape Gooseberry" },
      { name: "Pepino Melon" },
    ],
  },
  {
    name: "Vegetables — Gourds & Cucurbits",
    icon: "ri-shape-line",
    crops: [
      { name: "Cucumber", varieties: ["Slicing", "Pickling", "English", "Persian", "Armenian", "Lemon"] },
      { name: "Pumpkin", varieties: ["Jack-o-Lantern", "Sugar Pie", "Cinderella", "Cushaw", "Kabocha"] },
      { name: "Winter Squash", varieties: ["Butternut", "Acorn", "Spaghetti", "Hubbard", "Delicata", "Buttercup"] },
      { name: "Summer Squash / Zucchini", varieties: ["Green Zucchini", "Yellow", "Crookneck", "Pattypan"] },
      { name: "Bottle Gourd (Lauki)" },
      { name: "Bitter Gourd (Karela)" },
      { name: "Ridge Gourd (Turai)" },
      { name: "Snake Gourd" },
      { name: "Sponge Gourd (Luffa)" },
      { name: "Ash Gourd (Winter Melon)" },
      { name: "Chayote" },
      { name: "Ivy Gourd (Tindora)" },
    ],
  },
  {
    name: "Fruits — Tropical",
    icon: "ri-sun-line",
    crops: [
      { name: "Banana", varieties: ["Cavendish", "Plantain", "Red Banana", "Lady Finger", "Robusta", "Nendran", "Burro", "Blue Java"] },
      { name: "Mango", varieties: ["Alphonso", "Kesar", "Dasheri", "Langra", "Totapuri", "Banganapalli", "Sindhri", "Chaunsa", "Ataulfo", "Kent", "Keitt", "Tommy Atkins", "Haden"] },
      { name: "Pineapple", varieties: ["Smooth Cayenne", "MD-2 (Gold)", "Queen", "Red Spanish"] },
      { name: "Papaya", varieties: ["Red Lady", "Solo", "Maradol", "Hawaiian"] },
      { name: "Guava", varieties: ["White", "Pink", "Allahabad Safeda", "Lalit", "Thai"] },
      { name: "Jackfruit" },
      { name: "Breadfruit" },
      { name: "Avocado", varieties: ["Hass", "Fuerte", "Reed", "Pinkerton", "Bacon", "Lamb Hass"] },
      { name: "Dragon Fruit (Pitaya)", varieties: ["White Flesh", "Red Flesh", "Yellow"] },
      { name: "Passion Fruit", varieties: ["Purple", "Yellow"] },
      { name: "Durian", varieties: ["Musang King", "D24", "Monthong"] },
      { name: "Rambutan" },
      { name: "Longan" },
      { name: "Lychee" },
      { name: "Mangosteen" },
      { name: "Soursop (Graviola)" },
      { name: "Custard Apple (Sitaphal)" },
      { name: "Sapodilla (Chikoo)" },
      { name: "Star Fruit (Carambola)" },
      { name: "Tamarind" },
      { name: "Date", varieties: ["Medjool", "Deglet Noor", "Barhi", "Halawi", "Zahidi"] },
      { name: "Fig", varieties: ["Black Mission", "Brown Turkey", "Kadota", "Calimyrna"] },
      { name: "Pomegranate", varieties: ["Wonderful", "Ganesh", "Bhagwa", "Kandhari"] },
      { name: "Persimmon", varieties: ["Fuyu", "Hachiya", "Sharon Fruit"] },
      { name: "Acerola" },
      { name: "Cherimoya" },
      { name: "Loquat" },
      { name: "Jujube (Ber)" },
      { name: "Wood Apple (Bael)" },
      { name: "Carob" },
    ],
  },
  {
    name: "Fruits — Citrus",
    icon: "ri-leaf-line",
    crops: [
      { name: "Orange", varieties: ["Valencia", "Navel", "Blood", "Cara Cara", "Hamlin"] },
      { name: "Mandarin", varieties: ["Clementine", "Satsuma", "Tangerine", "Kinnow", "Nagpur", "Dancy"] },
      { name: "Lemon", varieties: ["Eureka", "Lisbon", "Meyer", "Ponderosa"] },
      { name: "Lime", varieties: ["Persian (Tahiti)", "Key", "Kaffir", "Finger Lime"] },
      { name: "Grapefruit", varieties: ["Ruby Red", "Pink", "White (Marsh)", "Star Ruby"] },
      { name: "Pomelo" },
      { name: "Citron" },
      { name: "Yuzu" },
      { name: "Bergamot" },
      { name: "Sweet Lime (Mosambi)" },
      { name: "Calamansi" },
      { name: "Buddha's Hand" },
    ],
  },
  {
    name: "Fruits — Pome & Stone",
    icon: "ri-checkbox-blank-circle-line",
    crops: [
      { name: "Apple", varieties: ["Gala", "Fuji", "Granny Smith", "Honeycrisp", "Red Delicious", "Golden Delicious", "Pink Lady", "Braeburn", "McIntosh", "Cortland", "Empire", "Cripps Pink", "Jonagold", "Kashmiri"] },
      { name: "Pear", varieties: ["Bartlett", "Anjou", "Bosc", "Comice", "Asian Pear (Nashi)", "Conference", "Williams"] },
      { name: "Quince" },
      { name: "Peach", varieties: ["Freestone", "Clingstone", "Donut (Saturn)", "White"] },
      { name: "Nectarine" },
      { name: "Plum", varieties: ["European", "Japanese", "Damson", "Mirabelle", "Greengage", "Santa Rosa"] },
      { name: "Apricot", varieties: ["Blenheim", "Moorpark", "Tilton", "Tomcot"] },
      { name: "Cherry", varieties: ["Bing", "Rainier", "Sweetheart", "Sour (Montmorency)", "Lapins", "Stella"] },
      { name: "Medlar" },
      { name: "Hawthorn" },
    ],
  },
  {
    name: "Fruits — Berries",
    icon: "ri-bubble-chart-line",
    crops: [
      { name: "Strawberry", varieties: ["June-bearing", "Everbearing", "Day-neutral", "Albion", "Camarosa", "Chandler"] },
      { name: "Blueberry", varieties: ["Highbush", "Lowbush", "Rabbiteye", "Half-high"] },
      { name: "Raspberry", varieties: ["Red", "Black", "Yellow", "Purple", "Summer-bearing", "Fall-bearing"] },
      { name: "Blackberry", varieties: ["Erect", "Trailing", "Thornless"] },
      { name: "Cranberry" },
      { name: "Gooseberry", varieties: ["European", "American", "Cape (Physalis)"] },
      { name: "Currant", varieties: ["Black", "Red", "White"] },
      { name: "Elderberry" },
      { name: "Mulberry", varieties: ["White", "Black", "Red"] },
      { name: "Boysenberry" },
      { name: "Loganberry" },
      { name: "Tayberry" },
      { name: "Goji Berry" },
      { name: "Sea Buckthorn" },
      { name: "Aronia (Chokeberry)" },
      { name: "Lingonberry" },
      { name: "Cloudberry" },
      { name: "Açaí" },
      { name: "Camu Camu" },
      { name: "Honeyberry (Haskap)" },
    ],
  },
  {
    name: "Fruits — Melons & Vine",
    icon: "ri-shape-2-line",
    crops: [
      { name: "Watermelon", varieties: ["Seeded", "Seedless", "Yellow Flesh", "Sugar Baby", "Crimson Sweet", "Charleston Gray"] },
      { name: "Muskmelon (Cantaloupe)", varieties: ["Athena", "Hales Best", "Charentais", "Galia"] },
      { name: "Honeydew" },
      { name: "Casaba Melon" },
      { name: "Crenshaw Melon" },
      { name: "Bitter Melon" },
      { name: "Grape", varieties: ["Table — Thompson Seedless", "Table — Concord", "Table — Flame", "Table — Red Globe", "Wine — Cabernet Sauvignon", "Wine — Merlot", "Wine — Chardonnay", "Wine — Pinot Noir", "Wine — Sauvignon Blanc", "Wine — Syrah", "Wine — Tempranillo", "Wine — Sangiovese", "Wine — Zinfandel", "Raisin"] },
      { name: "Kiwifruit", varieties: ["Hayward (Green)", "Gold", "Hardy"] },
    ],
  },
  {
    name: "Nuts",
    icon: "ri-walk-line",
    crops: [
      { name: "Almond", varieties: ["Nonpareil", "Carmel", "Mission", "Padre", "Marcona"] },
      { name: "Walnut", varieties: ["English (Persian)", "Black", "Chandler", "Hartley"] },
      { name: "Cashew" },
      { name: "Hazelnut (Filbert)" },
      { name: "Pistachio", varieties: ["Kerman", "Sirora", "Aegina"] },
      { name: "Pecan", varieties: ["Stuart", "Pawnee", "Desirable", "Cheyenne"] },
      { name: "Macadamia" },
      { name: "Brazil Nut" },
      { name: "Chestnut", varieties: ["Sweet (Castanea sativa)", "Chinese", "Japanese", "American"] },
      { name: "Pine Nut (Pignoli)" },
      { name: "Areca Nut (Betel Nut)" },
      { name: "Kola Nut" },
    ],
  },
  {
    name: "Herbs & Spices",
    icon: "ri-mist-line",
    crops: [
      { name: "Basil", varieties: ["Sweet (Genovese)", "Thai", "Holy (Tulsi)", "Lemon", "Purple"] },
      { name: "Mint", varieties: ["Peppermint", "Spearmint", "Chocolate", "Pineapple", "Apple"] },
      { name: "Coriander / Cilantro" },
      { name: "Parsley", varieties: ["Flat-leaf (Italian)", "Curly", "Hamburg"] },
      { name: "Dill" },
      { name: "Oregano" },
      { name: "Thyme", varieties: ["Common", "Lemon", "Creeping"] },
      { name: "Sage" },
      { name: "Rosemary" },
      { name: "Tarragon" },
      { name: "Chervil" },
      { name: "Marjoram" },
      { name: "Bay Leaf" },
      { name: "Lemongrass" },
      { name: "Curry Leaf" },
      { name: "Stevia" },
      { name: "Black Pepper" },
      { name: "Long Pepper" },
      { name: "Cardamom", varieties: ["Green", "Black"] },
      { name: "Cinnamon", varieties: ["Ceylon (True)", "Cassia"] },
      { name: "Clove" },
      { name: "Nutmeg / Mace" },
      { name: "Star Anise" },
      { name: "Anise" },
      { name: "Fennel" },
      { name: "Cumin" },
      { name: "Caraway" },
      { name: "Fenugreek (Methi Seed)" },
      { name: "Ajwain (Carom)" },
      { name: "Asafoetida (Hing)" },
      { name: "Vanilla", varieties: ["Bourbon", "Tahitian", "Mexican"] },
      { name: "Saffron" },
      { name: "Paprika" },
      { name: "Sumac" },
      { name: "Allspice (Pimento)" },
      { name: "Juniper" },
      { name: "Mahlab" },
      { name: "Mastic" },
      { name: "Annatto" },
      { name: "Tamarillo" },
    ],
  },
  {
    name: "Beverage & Cash Crops",
    icon: "ri-cup-line",
    crops: [
      { name: "Coffee", varieties: ["Arabica — Typica", "Arabica — Bourbon", "Arabica — Geisha", "Arabica — SL28", "Arabica — Caturra", "Arabica — Catuai", "Arabica — Heirloom", "Robusta", "Liberica", "Excelsa"] },
      { name: "Tea", varieties: ["Black (Assam)", "Black (Darjeeling)", "Black (Ceylon)", "Green (Sencha)", "Green (Matcha)", "Green (Longjing)", "White (Silver Needle)", "Oolong", "Pu-erh", "Yellow"] },
      { name: "Cocoa", varieties: ["Criollo", "Forastero", "Trinitario", "Nacional"] },
      { name: "Sugarcane", varieties: ["Co-86032", "Co-0238", "CP 88-1762", "B 49119"] },
      { name: "Sugar Beet" },
      { name: "Tobacco", varieties: ["Virginia (Flue-cured)", "Burley", "Oriental", "Maryland", "Latakia", "Connecticut Shade"] },
      { name: "Hops", varieties: ["Cascade", "Centennial", "Citra", "Mosaic", "Saaz", "Hallertau", "Fuggle"] },
      { name: "Yerba Mate" },
      { name: "Cola Nut" },
      { name: "Cacao Pod" },
      { name: "Hemp (Industrial)", varieties: ["Fiber", "Grain (Seed)", "CBD"] },
    ],
  },
  {
    name: "Fiber Crops",
    icon: "ri-shirt-line",
    crops: [
      { name: "Cotton", varieties: ["Upland (G. hirsutum)", "Pima/Egyptian (G. barbadense)", "Sea Island", "Bt Cotton"] },
      { name: "Jute" },
      { name: "Flax (Linen)" },
      { name: "Hemp (Fiber)" },
      { name: "Ramie" },
      { name: "Sisal" },
      { name: "Abaca (Manila Hemp)" },
      { name: "Kenaf" },
      { name: "Coir (Coconut Fiber)" },
      { name: "Bamboo (Fiber)" },
    ],
  },
  {
    name: "Fodder & Forage",
    icon: "ri-grass-line",
    crops: [
      { name: "Alfalfa (Lucerne)" },
      { name: "Clover", varieties: ["Red", "White", "Crimson", "Berseem", "Subterranean"] },
      { name: "Ryegrass", varieties: ["Annual (Italian)", "Perennial"] },
      { name: "Timothy" },
      { name: "Bermudagrass" },
      { name: "Tall Fescue" },
      { name: "Orchardgrass" },
      { name: "Sudangrass" },
      { name: "Vetch", varieties: ["Common", "Hairy"] },
      { name: "Napier Grass (Elephant Grass)" },
      { name: "Guinea Grass" },
      { name: "Sainfoin" },
      { name: "Mustard (Cover Crop)" },
      { name: "Tef (Forage)" },
      { name: "Forage Maize / Silage Corn" },
      { name: "Forage Sorghum" },
    ],
  },
  {
    name: "Mushrooms",
    icon: "ri-medal-line",
    crops: [
      { name: "Button (Agaricus)", varieties: ["White", "Cremini", "Portobello"] },
      { name: "Oyster", varieties: ["Pearl", "Pink", "Yellow (Golden)", "Blue", "King Oyster"] },
      { name: "Shiitake" },
      { name: "Enoki" },
      { name: "Maitake (Hen of the Woods)" },
      { name: "Lion's Mane" },
      { name: "Reishi" },
      { name: "Chestnut Mushroom" },
      { name: "Wine Cap (Stropharia)" },
      { name: "Beech Mushroom (Shimeji)" },
      { name: "Paddy Straw Mushroom" },
    ],
  },
  {
    name: "Flowers (Commercial)",
    icon: "ri-flower-line",
    crops: [
      { name: "Rose", varieties: ["Hybrid Tea", "Floribunda", "Damask", "Bourbon", "Climber", "Miniature"] },
      { name: "Marigold", varieties: ["African", "French", "Signet"] },
      { name: "Chrysanthemum" },
      { name: "Gerbera" },
      { name: "Tulip" },
      { name: "Lily", varieties: ["Asiatic", "Oriental", "Tiger", "Easter"] },
      { name: "Jasmine" },
      { name: "Lavender", varieties: ["English", "French", "Spanish"] },
      { name: "Sunflower (Ornamental)" },
      { name: "Carnation" },
      { name: "Gladiolus" },
      { name: "Tuberose" },
      { name: "Orchid", varieties: ["Phalaenopsis", "Cymbidium", "Dendrobium", "Vanda"] },
      { name: "Anthurium" },
      { name: "Hibiscus" },
      { name: "Heliconia" },
    ],
  },
  {
    name: "Specialty & Aquatic",
    icon: "ri-water-flash-line",
    crops: [
      { name: "Aloe Vera" },
      { name: "Sugarcane (Chewing)" },
      { name: "Bamboo (Edible Shoots)" },
      { name: "Banana (Plantain)" },
      { name: "Water Chestnut" },
      { name: "Water Spinach (Kangkong)" },
      { name: "Watercress" },
      { name: "Lotus" },
      { name: "Wasabi" },
      { name: "Spirulina" },
      { name: "Chlorella" },
      { name: "Microgreens (mixed)" },
      { name: "Sprouts (Alfalfa/Mung/Broccoli)" },
      { name: "Truffle", varieties: ["Black (Périgord)", "White (Alba)", "Summer", "Burgundy"] },
    ],
  },
];

// Flatten helper for fast search.
export function getAllCropEntries() {
  const out = [];
  for (const cat of CROP_CATEGORIES) {
    for (const c of cat.crops) {
      const varieties = c.varieties || [];
      out.push({ category: cat.name, crop: c.name, variety: null, label: c.name, sub: cat.name });
      for (const v of varieties) {
        out.push({ category: cat.name, crop: c.name, variety: v, label: `${c.name} · ${v}`, sub: cat.name });
      }
    }
  }
  return out;
}
